config/routes.rb
Rails.application.routes.draw do
  resources :links, only: [:show, :index, :new, :create]
  resources :analytics, only: [:show]

  root to: "links#new"
  get "/:short_url" => "links#redirect"
end

app/models/analytic.rb
class Analytic < ActiveRecord::Base
  belongs_to :link
  has_many :unique_visitors

  validates :visits, presence: true, numericality: true
  validates :unique_visits, presence: true, numericality: true

  def most_common_browser
    browsers = unique_visitors.all.group_by { |uv| uv.browser }
    if browsers.any?
      browser = browsers.sort_by { |b| -b[1].length }.first.first
    end
  end

  def most_common_platform
    platforms = unique_visitors.all.group_by { |uv| uv.platform }
    if platforms.any?
      platform = platforms.sort_by { |b| -b[1].length }.first.first
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  include Geokit::Geocoders
  has_one :analytic

  validates :long_url, presence: true, uniqueness: true
  validates :short_url, presence: true, uniqueness: true

  after_create :start_analyzing

  def shorten
    # created a random 6 character string
    characters = ["a", "b", "c", "d", "e", "f", "g",
                  "h", "i", "j", "k", "l", "m", "n",
                  "o", "p", "q", "r", "s", "t", "u",
                  "v", "w", "x", "y", "z", "A", "B",
                  "C", "D", "E", "F", "G", "H", "I",
                  "J", "K", "L", "M", "N", "O", "P",
                  "Q", "R", "S", "T", "U", "V", "W",
                  "X", "Y", "Z", "1", "2", "3", "4",
                  "5", "6", "7", "8", "9", "0"]
    path = ""
    6.times { path << characters[rand(61)] }
    if Link.all.select { |l| l.short_url == path }.any?
      self.shorten
    else
      self.short_url = path
    end
  end

  def start_analyzing
    Analytic.create(link: self)
  end

  def track_visits(request)
    analytic.increment!(:visits, by = 1)
    if !analytic.unique_visitors.any? { |uv| uv.visitor_ip == request.ip }
      browser = Browser.new(ua: request.env["HTTP_USER_AGENT"])
      country = location_from_ip(request.ip)
      analytic.unique_visitors.create(visitor_ip: request.ip,
                                      browser: browser.name,
                                      browser_version: browser.version,
                                      platform: browser.platform.capitalize,
                                      country: country)
      analytic.increment!(:unique_visits, by = 1)
    end
  end

  def self.most_popular
    joins(:analytic).order("analytics.visits").first(5)
  end

  def self.most_recent
    order("created_at DESC").first(5)
  end

  private

  def location_from_ip(ip)
    location = IpGeocoder.geocode(ip)
    location.country_code
  end
end

app/models/unique_visitor.rb
class UniqueVisitor < ActiveRecord::Base
  belongs_to :analytic

  validates :visitor_ip, presence: true
  validates :analytic_id, presence: true
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def show
    @analytics = Analytic.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
    @link = Link.find(params[:id])
  end

  def index
    @popular_links = Link.most_popular
    @recent_links = Link.most_recent
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.find_or_initialize_by(long_url: link_params[:long_url])
    @link.shorten if !@link.valid?
    if @link.save
      flash[:notice] = "Link created"
      redirect_to link_path(@link)
    else
      render :new
    end
  end

  def redirect
    link = Link.find_by(short_url: params[:short_url])
    if link
      link.track_visits(request)
      redirect_to link.long_url
    else
      flash[:error] = "Couldn't find that link"
      render :new
    end
  end

  private

  def link_params
    params.require("link").permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/analytics/show.html.erb
<div>
  Total visits: <%= @analytics.visits %>
</div>
<div>
  Unique visits: <%= @analytics.unique_visits %>
</div>
<div>
  Visitors' most common browser: <%= @analytics.most_common_browser %>
</div>
<div>
  Visitors' most common platform: <%= @analytics.most_common_platform %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gitly</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %>">
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<div class="most-popular">
  <h3>Most Visited Links</h3>
  <% @popular_links.each do |pop_link| %>
    <div>
      <%= pop_link.short_url %> | <%= pop_link.long_url %>
    </div>
  <% end %>
</div>

<div class="most-recent">
  <h3>Most Recent Links</h3>
  <% @recent_links.each do |recent_link| %>
    <div>
      <%= recent_link.short_url %> | <%= recent_link.long_url %>
    </div>
  <% end %>
</div>

app/views/links/new.html.erb
<%= form_for @link do |f| %>
  <%= f.label :long_url, "URL" %>
  <%= f.text_field :long_url %>

  <%= f.submit "Shorten" %>
<% end %>

app/views/links/show.html.erb
<div>
  Your shortened link is: <%= @link.short_url %>
</div>
<div>
  The URL it points to is: <%= @link.long_url %>
</div>
<div>
  <%= link_to "View Analytics", analytic_path(@link.analytic) %>
</div>